In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/rj7shakya/python_ml/main/cleaned_imdb.csv")
df.head(n=10)
# reads first five data

NameError: ignored

In [ ]:
df.columns

Index(['Unnamed: 0', 'color', 'director_name', 'num_critic_for_reviews',
       'duration', 'director_facebook_likes', 'actor_3_facebook_likes',
       'actor_2_name', 'actor_1_facebook_likes', 'gross', 'genres',
       'actor_1_name', 'movie_title', 'num_voted_users',
       'cast_total_facebook_likes', 'actor_3_name', 'facenumber_in_poster',
       'plot_keywords', 'movie_imdb_link', 'num_user_for_reviews', 'language',
       'country', 'content_rating', 'budget', 'title_year',
       'actor_2_facebook_likes', 'imdb_score', 'aspect_ratio',
       'movie_facebook_likes'],
      dtype='object')

In [ ]:
df = df.drop(columns = ['Unnamed: 0']) #delete the column
df

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.000000,178.0,0.0,855.0,Joel David Moore,1000.0,7.605058e+08,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.780000,33000
1,Color,Gore Verbinski,302.000000,169.0,563.0,1000.0,Orlando Bloom,40000.0,3.094042e+08,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.350000,0
2,Color,Sam Mendes,602.000000,148.0,0.0,161.0,Rory Kinnear,11000.0,2.000742e+08,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.350000,85000
3,Color,Christopher Nolan,813.000000,164.0,22000.0,23000.0,Christian Bale,27000.0,4.481306e+08,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.350000,164000
4,Color,Andrew Stanton,462.000000,132.0,475.0,530.0,Samantha Morton,640.0,7.305868e+07,Action|Adventure|Sci-Fi,...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.350000,24000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4549,Color,Neill Dela Llana,35.000000,80.0,0.0,0.0,Edgar Tancangco,0.0,7.007100e+04,Thriller,...,35.0,English,Philippines,Not Rated,7000.0,2005.0,0.0,6.3,1.841308,74
4550,Color,Robert Rodriguez,56.000000,81.0,0.0,6.0,Peter Marquardt,121.0,2.040920e+06,Action|Crime|Drama|Romance|Thriller,...,130.0,Spanish,USA,R,7000.0,1992.0,20.0,6.9,1.370000,0
4551,Color,Anthony Vallone,322.146105,84.0,2.0,2.0,John Considine,45.0,9.976776e+06,Crime|Drama,...,1.0,English,USA,PG-13,3250.0,2005.0,44.0,7.8,1.507071,4
4552,Color,Edward Burns,14.000000,95.0,0.0,133.0,Caitlin FitzGerald,296.0,4.584000e+03,Comedy|Drama,...,14.0,English,USA,Not Rated,9000.0,2011.0,205.0,6.4,2.508249,413
4553,Color,Jon Gunn,43.000000,90.0,16.0,16.0,Brian Herzlinger,86.0,8.522200e+04,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.850000,456

In [ ]:
df.head()

In [ ]:
df.tail()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
4549,Color,Neill Dela Llana,35.000000,80.0,0.0,0.0,Edgar Tancangco,0.0,7.007100e+04,Thriller,...,35.0,English,Philippines,Not Rated,7000.0,2005.0,0.0,6.3,1.841308,74
4550,Color,Robert Rodriguez,56.000000,81.0,0.0,6.0,Peter Marquardt,121.0,2.040920e+06,Action|Crime|Drama|Romance|Thriller,...,130.0,Spanish,USA,R,7000.0,1992.0,20.0,6.9,1.370000,0
4551,Color,Anthony Vallone,322.146105,84.0,2.0,2.0,John Considine,45.0,9.976776e+06,Crime|Drama,...,1.0,English,USA,PG-13,3250.0,2005.0,44.0,7.8,1.507071,4
4552,Color,Edward Burns,14.000000,95.0,0.0,133.0,Caitlin FitzGerald,296.0,4.584000e+03,Comedy|Drama,...,14.0,English,USA,Not Rated,9000.0,2011.0,205.0,6.4,2.508249,413
4553,Color,Jon Gunn,43.000000,90.0,16.0,16.0,Brian Herzlinger,86.0,8.522200e+04,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.850000,456

In [ ]:
df.loc[:]['director_name'] #read the

0           James Cameron
1          Gore Verbinski
2              Sam Mendes
3       Christopher Nolan
4          Andrew Stanton
              ...
4549     Neill Dela Llana
4550     Robert Rodriguez
4551      Anthony Vallone
4552         Edward Burns
4553             Jon Gunn
Name: director_name, Length: 4554, dtype: object

In [ ]:
df.loc[0:4][['movie_title','budget','imdb_score']]

                                 movie_title       budget  imdb_score
0                                    Avatar   237000000.0         7.9
1  Pirates of the Caribbean: At World's End   300000000.0         7.1
2                                   Spectre   245000000.0         6.8
3                     The Dark Knight Rises   250000000.0         8.5
4                               John Carter   263700000.0         6.6

In [ ]:
df.columns

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

In [ ]:
df.loc[0:5][['movie_title','budget','imdb_score','movie_facebook_likes']]

,movie_title,budget,imdb_score,movie_facebook_likes
0,Avatar,237000000.0,7.9,33000
1,Pirates of the Caribbean: At World's End,300000000.0,7.1,0
2,Spectre,245000000.0,6.8,85000
3,The Dark Knight Rises,250000000.0,8.5,164000
4,John Carter,263700000.0,6.6,24000
5,Spider-Man 3,258000000.0,6.2,0

In [1]:
# 
df.iloc[:,4]

NameError: ignored

In [ ]:
df.loc[1][:]

color                                                                    Color
director_name                                                   Gore Verbinski
num_critic_for_reviews                                                   302.0
duration                                                                 169.0
director_facebook_likes                                                  563.0
actor_3_facebook_likes                                                  1000.0
actor_2_name                                                     Orlando Bloom
actor_1_facebook_likes                                                 40000.0
gross                                                              309404152.0
genres                                                Action|Adventure|Fantasy
actor_1_name                                                       Johnny Depp
movie_title                          Pirates of the Caribbean: At World's End
num_voted_users                                                         471220
cast_total_facebook_likes                                                48350
actor_3_name                                                    Jack Davenport
facenumber_in_poster                                                       0.0
plot_keywords                goddess|marriage ceremony|marriage proposal|pi...
movie_imdb_link              http://www.imdb.com/title/tt0449088/?ref_=fn_t...
num_user_for_reviews                                                    1238.0
language                                                               English
country                                                                    USA
content_rating                                                           PG-13
budget                                                             300000000.0
title_year                                                              2007.0
actor_2_facebook_likes                                                  5000.0
imdb_score                                                                 7.1
aspect_ratio                                                              2.35
movie_facebook_likes                                                         0
Name: 1, dtype: object

In [ ]:
df.iloc[0,1]

NameError: ignored

In [ ]:
df.iloc[1:4,1]

1       Gore Verbinski
2           Sam Mendes
3    Christopher Nolan
Name: director_name, dtype: object

In [ ]:
df.iloc[1:4,5:7] # i points to index

   actor_3_facebook_likes    actor_2_name
1                  1000.0   Orlando Bloom
2                   161.0    Rory Kinnear
3                 23000.0  Christian Bale

In [ ]:
index = df.columns.get_loc('director_name')
index
df.iloc[:,index]

0           James Cameron
1          Gore Verbinski
2              Sam Mendes
3       Christopher Nolan
4          Andrew Stanton
              ...
4549     Neill Dela Llana
4550     Robert Rodriguez
4551      Anthony Vallone
4552         Edward Burns
4553             Jon Gunn
Name: director_name, Length: 4554, dtype: object

In [ ]:
df.sort_values(by=['director_facebook_likes'],ascending=True).head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
823,Color,Frank Oz,140.0,85.0,0.0,490.0,Adam Alexi-Malle,21000.0,66365290.0,Comedy,...,358.0,English,USA,PG-13,55000000.0,1999.0,860.0,6.4,1.37,0
3041,Color,David Lynch,143.0,112.0,0.0,201.0,Richard Farnsworth,874.0,6197866.0,Biography|Drama,...,414.0,English,France,G,10000000.0,1999.0,262.0,8.0,2.35,0
826,Color,Robert Zemeckis,49.0,104.0,0.0,812.0,Meryl Streep,13000.0,58422650.0,Comedy|Fantasy|Horror,...,173.0,English,USA,PG-13,55000000.0,1992.0,11000.0,6.4,1.85,8000
3039,Color,Timothy Björklund,33.0,74.0,0.0,719.0,Kelsey Grammer,886.0,6491350.0,Animation|Comedy|Family|Fantasy|Musical,...,26.0,English,USA,PG,10000000.0,2004.0,808.0,5.8,1.85,49

In [ ]:
df.sort_values(by=['budget'],ascending=False).loc[:6][['movie_title','budget']]

                                    movie_title        budget
2861                                  The Host   1.221550e+10
3645                            Lady Vengeance   4.200000e+09
2878                                  Fateless   2.500000e+09
2235                         Princess Mononoke   2.400000e+09
2246                                  Steamboy   2.127520e+09
3259                                     Akira   1.100000e+09
4209                             Godzilla 2000   1.000000e+09
2943                    Kabhi Alvida Naa Kehna   7.000000e+08
3143                            Trading Places   7.000000e+08
3637                                     Tango   7.000000e+08
4038                                  Stitches   6.758157e+08
1740   The Sisterhood of the Traveling Pants 2   5.863231e+08
4014                             Clockwatchers   5.702012e+08
1290                                 Red Cliff   5.536320e+08
4279                                    Charly   5.468606e+08
1283                         Because I Said So   5.419518e+08
1585                                Glory Road   4.883304e+08
2899                        Jackass Number Two   4.624059e+08
1450                  The Horseman on the Roof   4.337475e+08
3371                          The Four Seasons   4.292168e+08
618                        Dinner for Schmucks   4.283714e+08
3999                                Inside Job   4.206123e+08
1001                             Anna Karenina   4.109778e+08
2059                         For Colored Girls   4.064565e+08
3412                              Mr. Nice Guy   4.035329e+08
3160                  The Legend of Suriyothai   4.000000e+08
4374                          The Californians   3.950599e+08
979    The Messenger: The Story of Joan of Arc   3.900000e+08
2841                    Rachel Getting Married   3.719989e+08
3230                               The Inkwell   3.650385e+08
2681         The Diving Bell and the Butterfly   3.628854e+08
2705                   The Caveman's Valentine   3.621105e+08
3909                         Journey to Saturn   3.462949e+08
2575                                     U2 3D   3.423391e+08
3172    Ultramarines: A Warhammer 40,000 Movie   3.250785e+08
4001         Ghost Dog: The Way of the Samurai   3.250785e+08
3656                                Easy Money   3.151139e+08
2375                        Madea Goes to Jail   3.092980e+08
2896                                     Trash   3.065987e+08
3591                   Tucker and Dale vs Evil   3.000000e+08
2626                                 Ong-bak 2   3.000000e+08
1     Pirates of the Caribbean: At World's End   3.000000e+08
998                               Pirate Radio   2.948306e+08
1453                                The Lovers   2.864922e+08
2688                               Easy Virtue   2.810200e+08
2134                            The Stepfather   2.789467e+08
3120                                    Volver   2.789467e+08
4                                  John Carter   2.637000e+08
6                                      Tangled   2.600000e+08

In [ ]:
df.sort_values(by=['imdb_score'],ascending=False).head().loc[:][['movie_title','budget']]

                    movie_title       budget
1864  The Shawshank Redemption    25000000.0
3293             The Godfather     6000000.0
2714    The Godfather: Part II    13000000.0
65             The Dark Knight   185000000.0
4416              12 Angry Men      350000.0

In [ ]:
df.shape

(4554, 28)

In [ ]:
df.dropna?

In [ ]:
val = df.dropna()  # return data
val
# df.dropna(inplace=True)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.000000,178.0,0.0,855.0,Joel David Moore,1000.0,7.605058e+08,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.780000,33000
1,Color,Gore Verbinski,302.000000,169.0,563.0,1000.0,Orlando Bloom,40000.0,3.094042e+08,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.350000,0
2,Color,Sam Mendes,602.000000,148.0,0.0,161.0,Rory Kinnear,11000.0,2.000742e+08,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.350000,85000
3,Color,Christopher Nolan,813.000000,164.0,22000.0,23000.0,Christian Bale,27000.0,4.481306e+08,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.350000,164000
4,Color,Andrew Stanton,462.000000,132.0,475.0,530.0,Samantha Morton,640.0,7.305868e+07,Action|Adventure|Sci-Fi,...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.350000,24000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4549,Color,Neill Dela Llana,35.000000,80.0,0.0,0.0,Edgar Tancangco,0.0,7.007100e+04,Thriller,...,35.0,English,Philippines,Not Rated,7000.0,2005.0,0.0,6.3,1.841308,74
4550,Color,Robert Rodriguez,56.000000,81.0,0.0,6.0,Peter Marquardt,121.0,2.040920e+06,Action|Crime|Drama|Romance|Thriller,...,130.0,Spanish,USA,R,7000.0,1992.0,20.0,6.9,1.370000,0
4551,Color,Anthony Vallone,322.146105,84.0,2.0,2.0,John Considine,45.0,9.976776e+06,Crime|Drama,...,1.0,English,USA,PG-13,3250.0,2005.0,44.0,7.8,1.507071,4
4552,Color,Edward Burns,14.000000,95.0,0.0,133.0,Caitlin FitzGerald,296.0,4.584000e+03,Comedy|Drama,...,14.0,English,USA,Not Rated,9000.0,2011.0,205.0,6.4,2.508249,413
4553,Color,Jon Gunn,43.000000,90.0,16.0,16.0,Brian Herzlinger,86.0,8.522200e+04,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.850000,456

In [ ]:
# grouping of data
df.groupby(['title_year'])['budget'].mean()

<ipython-input-49-b14cbb32d5d6>:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df.groupby(['title_year'])['imdb_score','budget'].mean()

            imdb_score        budget
title_year
1916.0        8.000000  3.859070e+05
1925.0        8.300000  2.450000e+05
1927.0        8.300000  6.000000e+06
1929.0        7.150000  6.452747e+07
1930.0        7.800000  3.950000e+06
...                ...           ...
2012.0        6.303030  4.801066e+07
2013.0        6.413568  4.687214e+07
2014.0        6.300000  4.357012e+07
2015.0        6.133533  4.926142e+07
2016.0        6.336709  6.757634e+07

[90 rows x 2 columns]

In [ ]:
df.groupby(['title_year'])['budget'].max()

title_year
1916.0    3.859070e+05
1925.0    2.450000e+05
1927.0    6.000000e+06
1929.0    1.286759e+08
1930.0    3.950000e+06
              ...
2012.0    6.758157e+08
2013.0    2.250000e+08
2014.0    3.065987e+08
2015.0    2.864922e+08
2016.0    2.500000e+08
Name: budget, Length: 90, dtype: float64